require 'akamai_cloudlet_manager/base'
require 'akamai_cloudlet_manager/detail'
require 'akamai_cloudlet_manager/origin'
require 'akamai_cloudlet_manager/policy_version'
require 'akamai_cloudlet_manager/policy'
